services:
  gen:
    entrypoint:
      - /opt/octodns/env/bin/python
      - /octodns/gen.py
    image: octodns/cloudflare:2025.05
    init: true
    volumes:
      - ./:/octodns
    working_dir: /octodns

  shell:
    entrypoint:
      - /usr/bin/bash
    image: octodns/cloudflare:2025.05
    init: true
    volumes:
      - ./:/octodns
    working_dir: /octodns

  sync:
    entrypoint:
      - /opt/octodns/env/bin/octodns-sync
      - --config-file
      - ./config/production.yaml
    image: octodns/cloudflare:2025.05
    init: true
    volumes:
      - ./:/octodns
    working_dir: /octodns

  sync-doit:
    entrypoint:
      - /opt/octodns/env/bin/octodns-sync
      - --config-file
      - ./config/production.yaml
      - --doit
    image: octodns/cloudflare:2025.05
    init: true
    volumes:
      - ./:/octodns
    working_dir: /octodns
