---
'':
  - type: MX
    values:
      - exchange: route3.mx.cloudflare.net.
        preference: 11
      - exchange: route1.mx.cloudflare.net.
        preference: 15
      - exchange: route2.mx.cloudflare.net.
        preference: 64
  - type: TXT
    value: v=spf1 include:_spf.mx.cloudflare.net ~all

_dmarc:
  - type: TXT
    value: v=DMARC1\; p=none\; rua=mailto:william@subtlecoolness.com
