---
manager:
  max_workers: 2

providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./config
    default_ttl: 300
    enforce_order: false
  cloudflare:
    class: octodns_cloudflare.CloudflareProvider
    token: env/CLOUDFLARE_TOKEN

zones:
  lugolandscapingservices.com.:
    sources:
      - config
    targets:
      - cloudflare
  subtlecoolness.com.:
    sources:
      - config
    targets:
      - cloudflare
