{
  "manager": {
    "max_workers": 2
  },
  "providers": {
    "cloudflare": {
      "class": "octodns_cloudflare.CloudflareProvider",
      "token": "env/CLOUDFLARE_TOKEN"
    },
    "config": {
      "class": "octodns.provider.yaml.YamlProvider",
      "default_ttl": 300,
      "directory": "./config",
      "enforce_order": false
    }
  },
  "zones": {
    "lugolandscapingservices.com.": {
      "sources": [
        "config"
      ],
      "targets": [
        "cloudflare"
      ]
    },
    "subtlecoolness.com.": {
      "sources": [
        "config"
      ],
      "targets": [
        "cloudflare"
      ]
    }
  }
}