{
  "": [
    {
      "type": "A",
      "value": "45.79.10.128"
    },
    {
      "ttl": 3600,
      "type": "TXT",
      "values": [
        "MS=ms39318768",
        "google-site-verification=RxUAQK2lPrb8l0bltRH-OcplAFQYr-2sL3_xq-CqJxw",
        "v=spf1 include:outbound.mailhop.org ~all"
      ]
    },
    {
      "type": "MX",
      "values": [
        {
          "exchange": "aspmx.l.google.com.",
          "preference": 10
        },
        {
          "exchange": "alt1.aspmx.l.google.com.",
          "preference": 20
        },
        {
          "exchange": "alt2.aspmx.l.google.com.",
          "preference": 30
        },
        {
          "exchange": "aspmx2.googlemail.com.",
          "preference": 40
        },
        {
          "exchange": "aspmx3.googlemail.com.",
          "preference": 50
        }
      ]
    }
  ],
  "404": [
    {
      "type": "CNAME",
      "value": "coruscant.subtlecoolness.com."
    }
  ],
  "accio": [
    {
      "type": "CNAME",
      "value": "accio.netlify.app."
    }
  ],
  "acciojacksons": [
    {
      "type": "CNAME",
      "value": "coruscant.subtlecoolness.com."
    }
  ],
  "andromeda": [
    {
      "type": "CNAME",
      "value": "demo-andromeda.netlify.app."
    }
  ],
  "birthdayfeed": [
    {
      "type": "CNAME",
      "value": "birthdayfeed.fly.dev."
    }
  ],
  "blog": [
    {
      "type": "CNAME",
      "value": "blog-subtlecoolness-com.netlify.app."
    }
  ],
  "cal": [
    {
      "type": "CNAME",
      "value": "coruscant.subtlecoolness.com."
    }
  ],
  "coruscant": [
    {
      "type": "A",
      "value": "45.79.10.128"
    },
    {
      "type": "AAAA",
      "value": "2600:3c00::f03c:91ff:fe24:29ee"
    },
    {
      "type": "MX",
      "values": [
        {
          "exchange": "coruscant.subtlecoolness.com.",
          "preference": 10
        }
      ]
    }
  ],
  "coruscant.ts": [
    {
      "type": "A",
      "value": "100.67.215.117"
    }
  ],
  "duo-1651460024648-8e3e5c59._domainkey": [
    {
      "type": "TXT",
      "value": "v=DKIM1\\; k=rsa\\; s=email\\; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDLWiBESFejMDydnDE7ERkklPgnUsmXgpOQohtvBaEaNc+KVkXJ+1zxTuQmRzKIdraep9CQ9sz/l2+cymh2wszV/bWBC7AfaRUcSUNd/R0DRUJuomIgL2kHfI2sXI2dVANCnYek3oYfPbm5LcJRY3v6oHUbGJ+Y8iyds6DcyVBQKwIDAQAB"
    }
  ],
  "echoip": [
    {
      "type": "CNAME",
      "value": "coruscant.subtlecoolness.com."
    }
  ],
  "em8786": [
    {
      "type": "CNAME",
      "value": "u25937580.wl081.sendgrid.net."
    }
  ],
  "email.mg": [
    {
      "type": "CNAME",
      "value": "mailgun.org."
    }
  ],
  "felucia.ts": [
    {
      "type": "A",
      "value": "100.66.139.64"
    }
  ],
  "groupmemail": [
    {
      "type": "CNAME",
      "value": "coruscant.subtlecoolness.com."
    }
  ],
  "groupmemail-test": [
    {
      "type": "CNAME",
      "value": "coruscant.subtlecoolness.com."
    }
  ],
  "he-gave-me-my-ears": [
    {
      "type": "CNAME",
      "value": "ghs.google.com."
    }
  ],
  "iego.ts": [
    {
      "type": "A",
      "value": "100.107.200.103"
    }
  ],
  "jakku.ts": [
    {
      "type": "A",
      "value": "100.110.210.43"
    }
  ],
  "junk": [
    {
      "type": "CNAME",
      "value": "coruscant.subtlecoolness.com."
    }
  ],
  "krs._domainkey.mg": [
    {
      "type": "TXT",
      "value": "k=rsa\\; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDXdL1VkQmI026q2KW+mryp0xqaJsMZGxF96QrlaGO5kqFBPuH7SEJEBJWw305bHxsV30XSZwTLHDWVVm6R2PDMowf4ke3LFxPC7Sjbr8lnHWz/goVBZbNkVRkZCwh5LLcufwXI1hY3M/Q1Wkx9oGelJOfAxOEqj2mwL8ZQb+69mwIDAQAB"
    }
  ],
  "lpb": [
    {
      "type": "CNAME",
      "value": "coruscant.subtlecoolness.com."
    }
  ],
  "mail._domainkey": [
    {
      "type": "TXT",
      "value": "k=rsa\\;p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDeMVIzrCa3T14JsNY0IRv5/2V1/v2itlviLQBwXsa7shBD6TrBkswsFUToPyMRWC9tbR/5ey0nRBH0ZVxp+lsmTxid2Y2z+FApQ6ra2VsXfbJP3HE6wAO0YTVEJt1TmeczhEd2Jiz/fcabIISgXEdSpTYJhb0ct0VJRxcg4c8c7wIDAQAB"
    }
  ],
  "mandalore.ts": [
    {
      "type": "A",
      "value": "100.75.215.67"
    }
  ],
  "mg": [
    {
      "type": "TXT",
      "value": "v=spf1 include:mailgun.org ~all"
    },
    {
      "type": "MX",
      "values": [
        {
          "exchange": "mxa.mailgun.org.",
          "preference": 10
        },
        {
          "exchange": "mxb.mailgun.org.",
          "preference": 10
        }
      ]
    }
  ],
  "molly": [
    {
      "type": "CNAME",
      "value": "molly-subtlecoolness-com.netlify.app."
    }
  ],
  "python-rainwave-client": [
    {
      "type": "CNAME",
      "value": "python-rainwave-client.netlify.app."
    }
  ],
  "recipes": [
    {
      "type": "CNAME",
      "value": "jackson-family-recipes.netlify.app."
    }
  ],
  "rss": [
    {
      "type": "CNAME",
      "value": "coruscant.subtlecoolness.com."
    }
  ],
  "s1._domainkey": [
    {
      "type": "CNAME",
      "value": "s1.domainkey.u25937580.wl081.sendgrid.net."
    }
  ],
  "s2._domainkey": [
    {
      "type": "CNAME",
      "value": "s2.domainkey.u25937580.wl081.sendgrid.net."
    }
  ],
  "silly-sentences": [
    {
      "type": "CNAME",
      "value": "silly-sentences.netlify.app."
    }
  ],
  "tatooine.ts": [
    {
      "type": "A",
      "value": "100.116.13.60"
    }
  ],
  "wiki": [
    {
      "type": "CNAME",
      "value": "coruscant.subtlecoolness.com."
    }
  ],
  "www": [
    {
      "type": "CNAME",
      "value": "coruscant.subtlecoolness.com."
    }
  ],
  "yavin": [
    {
      "type": "CNAME",
      "value": "coruscant.subtlecoolness.com."
    }
  ]
}